import {
  LayoutDashboard,
  Building2,
  ShieldCheck,
  History,
  Landmark,
  Activity,
  FileCheck2,
  Settings,
  BookOpen,
  Users,
  Receipt,
  LifeBuoy,
  BarChart3,
  ClipboardCheck,
  Tag,
  Mail,
  PenTool,
  GraduationCap,
  Wallet,
  Star,
  Compass,
  ListChecks,
  Award,
  Heart,
  UserCheck,
  FileText,
  Film,
  ClipboardList,
  Send,
  Home,
  Search,
  ShoppingCart,
  CreditCard,
  ListTree,
  PlayCircle,
  HelpCircle,
  UserCog,
} from 'lucide-react';

export const ROLES = {
  superadmin: {
    id: 'superadmin',
    name: 'Super Admin',
    accent: 'superadmin',
    subdomain: 'admin.olma.io',
    badgeIcon: ShieldCheck,
    tagline: 'Platform oversight',
    nav: [
      { id: 'global-summary', label: 'Global Summary', icon: LayoutDashboard },
      { id: 'organizations', label: 'Organizations', icon: Building2 },
      { id: 'administrators', label: 'Administrator Accounts', icon: ShieldCheck },
      { id: 'audit-log', label: 'Audit Log', icon: History },
      { id: 'revenue', label: 'Revenue & Payouts', icon: Landmark },
      { id: 'platform-health', label: 'Platform Health', icon: Activity },
      { id: 'compliance', label: 'Compliance', icon: FileCheck2 },
      { id: 'settings', label: 'Settings', icon: Settings },
    ],
  },
  administrator: {
    id: 'administrator',
    name: 'Administrator',
    accent: 'administrator',
    subdomain: 'ops.olma.io',
    badgeIcon: Settings,
    tagline: 'Marketplace operations',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { id: 'approvals', label: 'Approval Queue', icon: ClipboardCheck },
      { id: 'courses', label: 'Courses', icon: BookOpen },
      { id: 'users', label: 'Users', icon: Users },
      { id: 'transactions', label: 'Transactions', icon: Receipt },
      { id: 'tickets', label: 'Support Tickets', icon: LifeBuoy },
      { id: 'plans', label: 'Subscription Plans', icon: Tag },
      { id: 'templates', label: 'Template Library', icon: Mail },
      { id: 'reports', label: 'Reports', icon: BarChart3 },
      { id: 'settings', label: 'Settings', icon: Settings },
    ],
  },
  creator: {
    id: 'creator',
    name: 'Creator',
    accent: 'creator',
    subdomain: 'creator.olma.io',
    badgeIcon: PenTool,
    tagline: 'Course studio',
    nav: [
      { id: 'onboarding', label: 'Onboarding & Verification', icon: UserCheck },
      { id: 'my-courses', label: 'Course List', icon: BookOpen },
      { id: 'course-basics', label: 'Course Basics', icon: FileText },
      { id: 'curriculum', label: 'Curriculum Builder', icon: PenTool },
      { id: 'media', label: 'Media Manager', icon: Film },
      { id: 'assessments', label: 'Assessments', icon: ClipboardList },
      { id: 'submit-review', label: 'Submit for Review', icon: Send },
      { id: 'students', label: 'Students', icon: GraduationCap },
      { id: 'earnings', label: 'Earnings Dashboard', icon: Wallet },
      { id: 'reviews', label: 'Reviews', icon: Star },
      { id: 'support', label: 'Raise a Ticket', icon: LifeBuoy },
    ],
  },
  subscriber: {
    id: 'subscriber',
    name: 'Subscriber',
    accent: 'subscriber',
    subdomain: 'learn.olma.io',
    badgeIcon: GraduationCap,
    tagline: 'Learning space',
    nav: [
      { id: 'dashboard', label: 'Home Page', icon: Home },
      { id: 'course-detail', label: 'Course Detail', icon: Compass },
      { id: 'catalog', label: 'Search Results', icon: Search },
      { id: 'plans', label: 'View Plans', icon: Tag },
      { id: 'cart', label: 'Cart & Checkout', icon: ShoppingCart },
      { id: 'subscription', label: 'Subscription Management', icon: CreditCard },
      { id: 'purchase-history', label: 'Purchase History', icon: Receipt },
      { id: 'my-learning', label: 'My Courses', icon: BookOpen },
      { id: 'progress', label: 'Progress Dashboard', icon: ListChecks },
      { id: 'section-overview', label: 'Course Section Overview', icon: ListTree },
      { id: 'player', label: 'Content Player', icon: PlayCircle },
      { id: 'assessments', label: 'Assessments', icon: HelpCircle },
      { id: 'messages', label: 'Raise a Ticket', icon: LifeBuoy },
      { id: 'account', label: 'Account & Security', icon: UserCog },
      { id: 'certificates', label: 'Certificates', icon: Award },
      { id: 'wishlist', label: 'Wishlist', icon: Heart },
    ],
  },
};

export const ROLE_ORDER = ['superadmin', 'administrator', 'creator', 'subscriber'];
