import {
  LayoutDashboard,
  Building2,
  ShieldCheck,
  History,
  Landmark,
  Activity,
  FileCheck2,
  Settings,
  BookOpen,
  Users,
  Receipt,
  LifeBuoy,
  BarChart3,
  ClipboardCheck,
  Tag,
  Mail,
  PenTool,
  GraduationCap,
  Wallet,
  Star,
  MessagesSquare,
  Compass,
  ListChecks,
  Award,
  Heart,
} from 'lucide-react';

export const ROLES = {
  superadmin: {
    id: 'superadmin',
    name: 'Super Admin',
    accent: 'superadmin',
    subdomain: 'admin.olma.io',
    badgeIcon: ShieldCheck,
    tagline: 'Platform oversight',
    nav: [
      { id: 'global-summary', label: 'Global Summary', icon: LayoutDashboard },
      { id: 'organizations', label: 'Organizations', icon: Building2 },
      { id: 'administrators', label: 'Administrator Accounts', icon: ShieldCheck },
      { id: 'audit-log', label: 'Audit Log', icon: History },
      { id: 'revenue', label: 'Revenue & Payouts', icon: Landmark },
      { id: 'platform-health', label: 'Platform Health', icon: Activity },
      { id: 'compliance', label: 'Compliance', icon: FileCheck2 },
      { id: 'settings', label: 'Settings', icon: Settings },
    ],
  },
  administrator: {
    id: 'administrator',
    name: 'Administrator',
    accent: 'administrator',
    subdomain: 'ops.olma.io',
    badgeIcon: Settings,
    tagline: 'Marketplace operations',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { id: 'approvals', label: 'Approval Queue', icon: ClipboardCheck },
      { id: 'courses', label: 'Courses', icon: BookOpen },
      { id: 'users', label: 'Users', icon: Users },
      { id: 'transactions', label: 'Transactions', icon: Receipt },
      { id: 'tickets', label: 'Support Tickets', icon: LifeBuoy },
      { id: 'plans', label: 'Subscription Plans', icon: Tag },
      { id: 'templates', label: 'Template Library', icon: Mail },
      { id: 'reports', label: 'Reports', icon: BarChart3 },
      { id: 'settings', label: 'Settings', icon: Settings },
    ],
  },
  creator: {
    id: 'creator',
    name: 'Creator',
    accent: 'creator',
    subdomain: 'creator.olma.io',
    badgeIcon: PenTool,
    tagline: 'Course studio',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { id: 'my-courses', label: 'My Courses', icon: BookOpen },
      { id: 'curriculum', label: 'Curriculum Builder', icon: PenTool },
      { id: 'students', label: 'Students', icon: GraduationCap },
      { id: 'earnings', label: 'Earnings', icon: Wallet },
      { id: 'reviews', label: 'Reviews', icon: Star },
      { id: 'messages', label: 'Messages', icon: MessagesSquare },
    ],
  },
  subscriber: {
    id: 'subscriber',
    name: 'Subscriber',
    accent: 'subscriber',
    subdomain: 'learn.olma.io',
    badgeIcon: GraduationCap,
    tagline: 'Learning space',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { id: 'my-learning', label: 'My Learning', icon: Compass },
      { id: 'catalog', label: 'Browse Catalog', icon: BookOpen },
      { id: 'progress', label: 'Progress', icon: ListChecks },
      { id: 'certificates', label: 'Certificates', icon: Award },
      { id: 'wishlist', label: 'Wishlist', icon: Heart },
      { id: 'messages', label: 'Messages', icon: MessagesSquare },
    ],
  },
};

export const ROLE_ORDER = ['superadmin', 'administrator', 'creator', 'subscriber'];
